import Head from "next/head";
import Image from "next/image";
// import styles from '@/styles/Home.module.css';
import { LogoGithub, LogoLinkedin, LogoNodejs } from "react-ionicons";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Nate Jahnke Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div class="mx-auto max-w-screen-lg px-3 py-6">
          <div class="flex flex-col gap-y-3 sm:flex-row sm:items-center sm:justify-between">
            <a href="#">
              <div class="flex items-center bg-gradient-to-br from-sky-500 to-cyan-400 bg-clip-text text-xl font-bold text-transparent">
                <svg
                  class="mr-1 h-10 w-10 stroke-cyan-600"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke-width="1.5"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M0 0h24v24H0z" stroke="none"></path>
                  <rect x="3" y="12" width="6" height="8" rx="1"></rect>
                  <rect x="9" y="8" width="6" height="12" rx="1"></rect>
                  <rect x="15" y="4" width="6" height="16" rx="1"></rect>
                  <path d="M4 20h14"></path>
                </svg>
                Nate's Portfolio
              </div>
            </a>
            <nav>
              <ul class="flex gap-x-3 font-medium text-gray-200">
                <li class="hover:text-white">
                  <a href="#projects">Projects</a>
                </li>
                <li class="hover:text-white">
                  <a href="https://github.com/natejahnke">GitHub</a>
                </li>
                <li class="hover:text-white">
                  <a href="https://www.linkedin.com/in/nathanjahnke/">
                    LinkedIn
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <div className="mx-auto max-w-screen-lg px-3 py-6">
          <div className="flex flex-col items-center md:flex-row md:justify-between md:gap-x-24">
            <div>
              <h1 className="text-3xl font-bold">Hello, I'm Nate Jahnke</h1>

              <p className="mt-6 text-xl leading-9">
                As an experienced IT Support professional, I have developed
                transferable skills that are valuable in software engineering
                and web development. My attention to detail, problem-solving
                abilities, and strong communication skills have equipped me to
                collaborate effectively with team members and clients to develop
                high-quality applications. I am confident that my experience in
                IT Support, coupled with my passion for coding, will enable me
                to excel in software engineering and web development roles.
              </p>
              <div className="mt-3 flex gap-1">
                <a href="https://www.linkedin.com/in/nathanjahnke/">
                  <LogoLinkedin
                    height="48px"
                    width="48px"
                    cssClasses="h-12 w-12 hover:translate-y-1"
                    color="#FFFFFF"
                  />
                </a>
                <a href="https://github.com/natejahnke">
                  <LogoGithub
                    height="48px"
                    width="48px"
                    cssClasses="h-12 w-12 hover:translate-y-1"
                    color="#FFFFFF"
                  />
                </a>
                <button
                  class="ml-2 shrink-0 rounded-full bg-gradient-to-br from-sky-500 to-cyan-400 px-8 py-1 text-xl font-medium hover:from-sky-700 hover:to-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-600/50"
                  type="submit"
                  onClick={() =>
                    (window.location.href =
                      "https://www.linkedin.com/in/nathanjahnke/")
                  }
                >
                  Resume
                </button>
              </div>
            </div>
            <div className="shrink-0">
              <img
                className="h-80 w-64 object-cover rounded-full border-2 border-white"
                src="/nate.png"
                alt="Avatar image"
                loading="lazy"
              />
            </div>
          </div>
        </div>
        <div id="projects" className="mx-auto max-w-screen-lg px-3 py-6">
          <div className="mb-6 text-2xl font-bold">
            Recent{" "}
            <span className="bg-gradient-to-br from-sky-500 to-cyan-400 bg-clip-text text-transparent">
              Projects
            </span>
          </div>
          <div className="flex flex-col gap-6">
            <div className="flex flex-col items-center gap-x-8 rounded-md bg-slate-800 p-3 md:flex-row">
              <div className="shrink-0">
                <a href="/demo/astro-boilerplate">
                  <img
                    className="h-36 w-36 hover:translate-y-1"
                    src="wildlifeexplorer.png"
                    alt="Project Web Design"
                    loading="lazy"
                    title=""
                  />
                </a>
              </div>
              <div>
                <div className="flex flex-col items-center gap-y-2 md:flex-row">
                  <a
                    className="hover:text-cyan-400"
                    href="/demo/astro-boilerplate"
                  >
                    <div className="text-xl font-semibold">
                      AI Wildlife Explorer
                    </div>
                  </a>
                  <div class="ml-3 flex gap-2">
                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-fuchsia-400 text-fuchsia-900">
                      Next.js
                    </div>
                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-sky-400 text-sky-900">
                      React.js
                    </div>
                    <div class="rounded-md px-2 py-1 text-xs font-semibold bg-lime-400 text-lime-900">
                      Tailwind CSS
                    </div>
                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-sky-400 text-sky-900">
                      Azure Computer Vision API
                    </div>
                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-rose-400 text-rose-900">
                      OpenAI API
                    </div>
                  </div>
                </div>
                <p class="mt-3 text-gray-400">
                  AI Wildlife Explorer is a personal web development project
                  that showcases the developer's skills in creating an
                  application that utilizes AI technology. It allows users to
                  upload images of animals to receive an AI-generated response
                  describing the animal, and also provides structured
                  information about the animal's habitat, diet, physical
                  characteristics, behavior, and conservation status. The app
                  features a modern, clean user interface and is built using
                  Next.js 13, Tailwind CSS, React, and React Ionicons.
                </p>
              </div>
            </div>
            <div className="flex flex-col items-center gap-x-8 rounded-md bg-slate-800 p-3 md:flex-row">
              <div className="shrink-0">
                <a href="/demo/astro-boilerplate">
                  <img
                    className="h-36 w-36 hover:translate-y-1"
                    src="fish.png"
                    alt="Project Web Design"
                    loading="lazy"
                    title=""
                  />
                </a>
              </div>
              <div>
                <div className="flex flex-col items-center gap-y-2 md:flex-row">
                  <a
                    className="hover:text-cyan-400"
                    href="/demo/astro-boilerplate"
                  >
                    <div className="text-xl font-semibold">
                      Fish of Minnesota
                    </div>
                  </a>
                  <div class="ml-3 flex gap-2">
                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-fuchsia-400 text-fuchsia-900">
                      Next.js
                    </div>
                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-sky-400 text-sky-900">
                      React.js
                    </div>
                    <div class="rounded-md px-2 py-1 text-xs font-semibold bg-lime-400 text-lime-900">
                      Tailwind CSS
                    </div>

                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-rose-500 text-sky-900">
                      Sanity.io CMS
                    </div>
                  </div>
                </div>
                <p class="mt-3 text-gray-400">
                  Fish of Minnesota is a modern and visually appealing web
                  application that provides a comprehensive gallery of fish
                  species found in Minnesota. The site is built with the latest
                  web development technologies, making it highly responsive and
                  performant. Users can easily navigate the site and access
                  detailed information about each fish species, enhancing their
                  knowledge of the fish population in Minnesota.
                </p>
              </div>
            </div>
            <div className="flex flex-col items-center gap-x-8 rounded-md bg-slate-800 p-3 md:flex-row">
              <div className="shrink-0">
                <a href="/demo/astro-boilerplate">
                  <img
                    className="rounded-full h-36 w-36 hover:translate-y-1"
                    src="fight.png"
                    alt="Project Web Design"
                    loading="lazy"
                    title=""
                  />
                </a>
              </div>
              <div>
                <div className="flex flex-col items-center gap-y-2 md:flex-row">
                  <a
                    className="hover:text-cyan-400"
                    href="/demo/astro-boilerplate"
                  >
                    <div className="text-xl font-semibold">UFC Event React</div>
                  </a>
                  <div class="ml-3 flex gap-2">
                    <div className="rounded-md px-2 py-1 text-xs font-semibold bg-sky-400 text-sky-900">
                      React.js
                    </div>
                  </div>
                </div>
                <p class="mt-3 text-gray-400">
                  UFC Event React is a dynamic web application showcasing the
                  developer's skill in creating seamless user experiences for
                  MMA fans. Built with React.js and custom CSS, the app features
                  an interactive fight card grid and a prominent current matchup
                  display. Users can easily update the main fight component by
                  selecting different matchups, demonstrating the developer's
                  ability to create responsive, engaging, and niche-specific
                  applications.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
